language: go

go:
  - 1.1
  - 1.2
  - 1.3
  - release
  - tip

addons:
  postgresql: "9.3"

services:
  - redis-server

before_install:
  - go get github.com/kr/godep
  - go get github.com/asm-products/readraptor

before_script:
  - psql -c 'create database rr_test;' -U postgres

script:
  - godep go test ./...